### ISSUE TITLE
see 'Loading screen...' for a long time

### ISSUE THREAD

**Issue by candacesmith** [BravoGroup/PADonors#14]
I tried to do a search for January 2016 and it seems 'stuck' on loading screen.  Are there no results?  too many results? I can't tell from this.

![image](https://user-images.githubusercontent.com/4052183/35569860-ca976bfe-05a3-11e8-82e1-71a935d51790.png)

**Comment by droganov** [comment]
@candacesmith I think it's a same as https://github.com/BravoGroup/PADonors/issues/7
