### ISSUE TITLE
City field not searching properly

### ISSUE THREAD

**Issue by HershGupta** [BravoGroup/PADonors#17]
I searched for "PAC" donations in "Harrisburg"

![screenshot-2018-2-1 pa donor haystack](https://user-images.githubusercontent.com/26412562/35683786-0d121d2c-0733-11e8-9276-6f2fa37c7b93.png)

The results apparently did not filter by city:

![screenshot-2018-2-1 pa donor haystack 1](https://user-images.githubusercontent.com/26412562/35683867-41f1423e-0733-11e8-8b3b-f86e4958a940.png)

**Comment by noahspoke** [comment]
Hey Hersh, I'm aware of this bug, thanks for flagging though. There were a few other tasks I needed to finish before implementing the new logic for this on production and staging. This will be released later today.

**Comment by noahspoke** [comment]
This feature will be added after initial staging beta release.
