### ISSUE TITLE
How do you indicate an Or or AND search?

### ISSUE THREAD

**Issue by candacesmith** [BravoGroup/PADonors#32]
It seems if I put multiple words in the search it is using an OR join, I would expect it woudl be an AND, maybe have some indicator of what the search rules are or some way to switch between AND/OR.

**Comment by noahspoke** [comment]
By default it is currently `OR` per CB

**Comment by HershGupta** [comment]
Just spoke with CB - he'd like to switch it to AND joins.

**Comment by noahspoke** [comment]
Yeah CB originally wanted it to be `OR`, which is why that's the current default.

**Comment by noahspoke** [comment]
@HershGupta Is there a pressing timeline on this specifically?

**Comment by HershGupta** [comment]
@noahspoke it's not pressing, but we would want it implemented in the near term - certainly before the launch.

**Comment by noahspoke** [comment]
@HershGupta @candacesmith Should I change to `AND` by default????

**Comment by candacesmith** [comment]
@noahspoke Yes, I think AND by default (and OR can be completed later, we may need some design work for that)

**Comment by noahspoke** [comment]
@candacesmith @HershGupta All searches are now `AND` will close when I push changes

**Comment by datracka** [comment]
Not valid anymore.
