### ISSUE TITLE
Sort only works twice

### ISSUE THREAD

**Issue by HershGupta** [BravoGroup/PADonors#37]
When I click a table header for the column in order to sort by it, I can only do so twice. Clicking more than two times doesn't re-sort the table. This affects "Recipient", "Date", and "Amount" columns. 

![haystacksort](https://user-images.githubusercontent.com/26412562/38095485-96bdb19e-333e-11e8-979c-c307d0a58266.gif)

**Comment by candacesmith** [comment]
@noahspoke I still see this happening are all these fixes in staging?

**Comment by candacesmith** [comment]
@noahspoke actually I think it's not the same problem, I think it's that can't sort by recipient.
