### ISSUE TITLE
Donor name looks like a link but it doesn't go anywhere

### ISSUE THREAD

**Issue by candacesmith** [BravoGroup/PADonors#47]
It either should do something or not be a link

![image](https://user-images.githubusercontent.com/4052183/39209927-a0c3b086-47dd-11e8-95ad-2c73a61c01bc.png)

**Comment by noahspoke** [comment]
Yes, it should be the front end for that page is very iffy at the moment. Not sure if we should include it in this iteration.

**Comment by datracka** [comment]
Not valid anymore.
