### ISSUE TITLE
What is this drop box supposed to do?  

### ISSUE THREAD

**Issue by candacesmith** [BravoGroup/PADonors#48]
Why have a drop box if all it does is go to the home page? If it shows saved searches, but the user doesn't have an account, maybe have an indicator that they can save the search there?  

![image](https://user-images.githubusercontent.com/4052183/39210887-6becdb8c-47e0-11e8-846e-90151594a67f.png)

**Comment by noahspoke** [comment]
@candacesmith Yeah, honestly I'm not sure what to do about that. Should I have Leonard find a better way to present this. Or just include save and then prompt account creation??

**Comment by datracka** [comment]
Not valid anymore.
