### ISSUE TITLE
Following button on home page?

### ISSUE THREAD

**Issue by candacesmith** [BravoGroup/PADonors#52]
What does this button do if the user doesn't have an account or isn't logged in or isn't following anything?  Maybe have it only appear if relevant.

![image](https://user-images.githubusercontent.com/4052183/39265803-94cab40c-489e-11e8-9d55-c4db9c60cf53.png)

**Comment by noahspoke** [comment]
Yes thanks for flagging, this should only appear to authed users.

**Comment by datracka** [comment]
Not valid anymore.
