### ISSUE TITLE
Chart name widths and text-overflow

### ISSUE THREAD

**Issue by noahspoke** [BravoGroup/PADonors#60]
https://www.dropbox.com/s/jylhetajv154x69/Screenshot%202018-05-18%2013.14.41.png?dl=0

<img width="459" alt="screenshot 2018-05-18 13 14 41" src="https://user-images.githubusercontent.com/6251554/40248325-950fed54-5a9d-11e8-9b58-9c8ae82f2561.png">

**Comment by datracka** [comment]
Not valid anymore.
